#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi_percentage;
my $acpi_state;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the percentage line of the "upower" command output
open (ACPI, "upower -i /org/freedesktop/UPower/devices/battery_BAT${bat_number} | grep 'percentage:' |") or die;
$acpi_percentage = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi_percentage !~ /\s*(\w+):\s*(\d+)%/) {
	die "Bad acpi percentage string: $acpi_percentage\n";
}

$percent = $2;
$full_text = "$percent%";

# read the state line of the "upower" command output
open (ACPI, "upower -i /org/freedesktop/UPower/devices/battery_BAT${bat_number} | grep 'state:' |") or die;
$acpi_state = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi_state !~ /\s*(\w+):\s*(\w+)/) {
	die "Bad acpi state string: $acpi_state\n";
}
$status = $2;

if ($status eq 'discharging') {
	$full_text .= ' DIS';
} elsif ($status eq 'charging') {
	$full_text .= ' CHR';
}

$short_text = $full_text;

#if ($acpi =~ /(\d\d:\d\d):/) {
#	$full_text .= " ($1)";
#}

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

	if ($percent < 20) {
		print "#FF0000\n";
	} elsif ($percent < 40) {
		print "#FFAE00\n";
	} elsif ($percent < 60) {
		print "#FFF600\n";
	} elsif ($percent < 85) {
		print "#A8FF00\n";
	}

	if ($percent < 5) {
		exit(33);
	}
}

exit(0);
