#!/usr/bin/env bash

################################
# Shows AUR packages that need updated.
#
# Dependencies:
# - checkupdates
# - yaourt
# - [notify-send]
#
# @return {Number}: Outdated packages
################################

case $BLOCK_BUTTON in
	1)
		gnome-terminal -- sh -c 'yaourt -Syu --aur ; echo \"Done...press any key\" ; pkill -RTMIN+12 i3blocks ; read -n 1' > /dev/null
	;;
esac

dir=$(dirname $0)
source $dir/util.sh

full=""
status=0

archPackages=$(checkupdates)
archResult=$?

if [ $archResult -eq 0 ] || [ $archResult -eq 2 ]
then
	aurPackages=$(yaourt -Quaq)
	numArchPackages=$(numLines "$archPackages")
	numAurPackages=$(numLines "$aurPackages")
	numAllPackages=$(calc "$numAurPackages + $numArchPackages")
	if [ "$numAllPackages" -gt "0" ]
	then
		color=\#FF0000
	else
		color=\#00FF00
	fi
else
	numArchPackages="-"
	numAurPackages="-"
	numAllPackages="-"
	color=\#FF0000
fi
#echo $numArchPackages
#echo $numAurPackages
#echo $numAllPackages

case $BLOCK_BUTTON in
	3)
		allPackages=$(echo 'arch';echo "$archPackages";echo 'aur';echo "$aurPackages")
		notify-send "Updates" "$allPackages"
	;;
esac

# print the results
echo "$numAllPackages"
echo "$numAllPackages"
echo $color

#echo $full
exit $status

